### ISSUE TITLE
Disable passkeys

### ISSUE THREAD

**Issue by IgnisDa** [teamhanko/hanko#1000]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Description

I would like to disable passkeys authentication for my instance since we do not want users to use it, and it just an additional step that hinders login.

### Describe your ideal solution

A key in the configuration that allows to disable this functionality.

### Workarounds or alternatives

None

### Hanko Version

v0.8.3

**Comment by FlxMgdnz** [comment]
Thanks for the feedback. We're working on the next iteration of the API that will allow much more flexibility in the settings. Enabling/disabling authentication methods individually is one of the new core features.

**Comment by IgnisDa** [comment]
Thanks! Is this being tracked in some other issue? I would like to follow it.

**Comment by FlxMgdnz** [comment]
Hey @IgnisDa I forgot to mention that you can disable passkeys when registering the component, see https://github.com/teamhanko/hanko/blob/main/frontend/elements/README.md

We currently don't have an issue to track the API rewrite.

**Comment by IgnisDa** [comment]
That's great. Maybe this issue can track the API rewrite status?

**Comment by FlxMgdnz** [comment]
> That's great. Maybe this issue can track the API rewrite status?

You can follow the development here https://github.com/teamhanko/hanko/tree/introduce_flowpilot

**Comment by FlxMgdnz** [comment]
This is now available.
