### ISSUE TITLE
Better support for both local development and deployed apps

### ISSUE THREAD

**Issue by FlxMgdnz** [teamhanko/hanko#1003]
Supporting local development and a deployed app currently requires:

1. Running two identical Hanko (Cloud) projects with different app URLs
2. Constantly changing the app URL of a single Hanko project

Both solutions are probably not ideal.

There are reasons why it is this way, though:
- WebAuthn (the API and protocol behind passkeys) is limited to a single origin, meaning you can't create a passkey that'll work on both http://localhost:3000 and https://yourapp.com. That's why we currently limit the app URL to one, i.e. the origin your passkeys will be created for.
- You'd probably don't want to share users / credentials / logs across local dev and prod environments, so separating the Hanko databases makes a lot of sense

Others (e.g. Stripe) allow to toggle between testing and live environments for a single "project", while all configuration and settings remain the same. Maybe we can achieve something similar by setting up two databases per project (testing/live).

Let's think about how we can improve the situation.

**Comment by like-a-bause** [comment]
To improve this situation I think we could do the following:
* Increase the project limit for the free tier on https://cloud.hanko.io  to 2-3.
* Add a "Copy Settings from project..." functionality in the New Project View

This way you don't have to do 2. which is annoying. I think the two database approach is a little implementation heavy and could potentially lead to confusion.
