### ISSUE TITLE
Improve UX for misconfigured app URL

### ISSUE THREAD

**Issue by FlxMgdnz** [teamhanko/hanko#1004]
If the app URL is not set to the correct value, Hanko users struggle with CORS issues.

I think it's safe to assume that whenever CORS happens, in 99.9% percent of the cases the reason is a misconfigured app URL.

Therefore, we should handle this scenario in Hanko frontend-sdk / Elements and display a more useful error message in the UI or at least as console output.

**Comment by like-a-bause** [comment]
I thought about displaying a nicer error message in case someone runs into a CORS error, but for security reasons there is no way to distinguish between a CORS error and some other network error (DNS,TLS...) See: https://stackoverflow.com/questions/4844643/is-it-possible-to-trap-cors-errors
and
https://stackoverflow.com/questions/19325314/how-to-detect-cross-origin-cors-error-vs-other-types-of-errors-for-xmlhttpreq

I would suggest two things:
* Put a warning  box about CORS in every guide and tutorial we have.
* Modify the Technical Error message to state something like "Please look into your browser console for further information"

**Comment by DarhkVoyd** [comment]
@FlxMgdnz @like-a-bause Hello, I'm a newcomer to this project and eager to help.Is this issue still open, and if so, how can I assist? What's the best way for me to get started?
