### ISSUE TITLE
Improve passkey naming

### ISSUE THREAD

**Issue by FlxMgdnz** [teamhanko/hanko#1027]
Add logic to Hanko Backend to suggest better fitting names for new passkeys.

Ideally, the result would look something like this:

Passkey name | Passkey source
-- | --
iCloud Keychain | iOS, macOS, iPadOS
Google Password Manager | Android
Chrome on Mac | macOS Chrome
Edge on Mac | macOS Edge
Windows Hello | Windows 10/11 device, Chrome, Edge, Firefox
1Password | 1Password
Dashlane | Dashlane
Security Key | Any roaming authenticator if somehow possible to identify
Passkey-98723 (current implementation) | If unknown / undefined

This can be done by using the AAGUIDs and this data:
https://github.com/passkeydeveloper/passkey-authenticator-aaguids

It can be expected that more providers will be added to the list over time.

We can use the icons later, but it's good to have them ready as well.

**Comment by ShatilKhan** [comment]
I want to work on this, please assign it to me.

**Comment by Rajarshi-Misra** [comment]
@FlxMgdnz I'm interested in working on this issue. If it hasn't been assigned to anyone yet, can you please assign it to me?

**Comment by FlxMgdnz** [comment]
Hey @ShatilKhan @Rajarshi-Misra if you want to work on this please open a draft PR, then we'll assign you.

**Comment by ShatilKhan** [comment]
Woking on it
Will make a Draft PR by today

**Comment by FlxMgdnz** [comment]
No PR so far, issue is still open
