### ISSUE TITLE
Improve passcode email default theme

### ISSUE THREAD

**Issue by FlxMgdnz** [teamhanko/hanko#1029]
The current passcode email sent by Hanko backend is just a very basic plain text email with no styling.

Before we introduce customizable HTML templates at some point, we can improve the current email by adding a basic HTML template.

The resulting template should contain the following information:

Subject:
`{passcode} is your passcode for {project_name}`

Body:
```
Enter the following passcode on your {project_name} authentication screen:

{passcode}


The passcode is valid for {passcode_lifetime} minutes.

If you didn't request a passcode, you can safely ignore this email.

```

![Image](https://user-images.githubusercontent.com/20115649/269013384-36e32f25-3ca2-4d14-8fe5-311f0cb6e8d3.png)

The luma email looks pretty cool.

![Image](https://user-images.githubusercontent.com/20115649/269002048-fd1c22fa-e22f-4503-8781-dfcb966760bb.png)

**Comment by Sranjan0208** [comment]
Can I work on this issue?

**Comment by Baghel-sumit** [comment]
Hi @FlxMgdnz , is this issue still open ? if yes, i m going to fix this.

**Comment by FlxMgdnz** [comment]
Hey @mrswastik-robot @Baghel-sumit I haven't heard back from @Sranjan0208 yet. So feel free to go for it if they don't respond today.

**Comment by Johnmiicheal** [comment]
@FlxMgdnz Can I also give it a try?

**Comment by Johnmiicheal** [comment]
@FlxMgdnz This is what I've designed

![image](https://github.com/teamhanko/hanko/assets/69642932/d95e679a-b102-4773-a6ba-1c0cdf9f47bd)

**Comment by TandinDev** [comment]
I did something like this :)

![Screenshot from 2023-10-07 17-07-55](https://github.com/teamhanko/hanko/assets/62091702/0e4f6860-551b-4c0b-ac16-6ff1739bc6fd)

**Comment by Its-Aman-Yadav** [comment]
Hey @FlxMgdnz, I also want to work with this issue
Kindly assign this to me, and I will work alongside other contributors.

**Comment by Fer-Win** [comment]
Hey @FlxMgdnz , is it fine i I can start working on it if u can assign this to me, I can do a good job since I am already experienced in creating Email Templates

**Comment by FlxMgdnz** [comment]
@Johnmiicheal I like your design, thanks. 

But I think we should use a standard font and not require any special / Google font for the email to render. 

I'll assign you now to this issue. If we don't hear back from you I'll have to assign another contributor.

**Comment by Johnmiicheal** [comment]
Oh, thank you very much. I'll work on it immediately.
> But I think we should use a standard font and not require any special / Google font for the email to render.

Yeah, alright then just plain old san-serif. Thanks again

**Comment by Johnmiicheal** [comment]
Hi @FlxMgdnz What folder should the new email template [html] file be in, I couldn't find any pointers apart from this directory
[https://github.com/teamhanko/hanko/blob/main/backend/mail/templates](https://github.com/teamhanko/hanko/blob/main/backend/mail/templates)

**Comment by jayakrishnan-jayu** [comment]
Hey @FlxMgdnz Can I work on this?

This is a template that i made based on the examples given above
<img width="576" alt="image" src="https://github.com/teamhanko/hanko/assets/25554170/05782738-f8ae-4576-a8a9-d5f35ef92c6d">

Also  can you advise me on the appropriate URL to use for the icon. I couldn't find an icon with black text from the Hanko website. The one in the above screenshot is a modified SVG version of the icon from hanko.io webpage. I don't think most of the email clients will render a SVG icon

**Comment by FlxMgdnz** [comment]
Will be dealt with when implementing the email template engine.
