### ISSUE TITLE
Improve readme for contributors

### ISSUE THREAD

**Issue by FlxMgdnz** [teamhanko/hanko#1031]
Add some instructions for new contributors to the base readme or CONTRIBUTING.md.

How to setup a local dev environment for Hanko?

Some examples:
- https://github.com/unkeyed/unkey/blob/main/.github/CONTRIBUTING.md
- https://github.com/documenso/documenso/blob/main/README.md#developer-setup

**Comment by ayan-joshi** [comment]
I would like to work on this issue if it's still an issue

**Comment by Vivek-GuptaXCode** [comment]
hello maintainers,is this issue open to work on? i would like to resolve this issue.

**Comment by Esther-Lita** [comment]
Hello everyone! For the first restructure of the Contribution guide we want to provide as much clarity as possible to the community, unfortunately this time this issue can only be worked from part of  the Hanko inside team. I hope you are willing to work on other of our issues, we'd be happy to count on you! 😎
