### ISSUE TITLE
[bug] : Pricing page has content misalignment

### ISSUE THREAD

**Issue by IAmRiteshKoushik** [teamhanko/hanko#1054]
### Describe the bug

The UI of the pricing page seems to have taken in some errors. Attaching a screenshot of the UI below. 

### Reproducing the bug

![image](https://github.com/teamhanko/hanko/assets/72215925/d373c90c-a4cc-4c27-8c59-bf64f751eb9a)

### Hanko Version

v1.0.2

### OS Hanko Backend

None

### OS

None

### Browser Version

Browser : Mozilla Firefox
Version : 117.0

### Environment

None

**Comment by Lokendrakushwah12** [comment]
can you please assign me this issue

**Comment by FlxMgdnz** [comment]
Thanks. We have to fix this in Webflow.
