### ISSUE TITLE
Next.js middleware

### ISSUE THREAD

**Issue by FlxMgdnz** [teamhanko/hanko#1061]
Let's come up with a middleware for Next.js that makes integration of Hanko as simple as possible.

We can take inspiration from https://clerk.com/docs/quickstarts/nextjs#protect-your-application.

**Comment by ayan-joshi** [comment]
I would like to work on this issue can u assign it under hacktoberfest label

**Comment by omzi** [comment]
I'd like to handle this should @ayan-joshi not be interested in it, @FlxMgdnz.

**Comment by whoami-anoint** [comment]
!assign

**Comment by FlxMgdnz** [comment]
Hey folks, thank you for you interest in contributing to Hanko. Please feel free to work on this. If there's no (draft) PR after 24h I will unassign you and the next one will be assigned.

**Comment by omzi** [comment]
Noted ✌🏽. 24hr is a bit too short though. How about 2/3 days please?

**Comment by FlxMgdnz** [comment]
How is it going @omzi ? You're on it?

**Comment by digant2482** [comment]
Hi @FlxMgdnz. Can I reference dub.sh middleware (since it is written fairly well). Also, may I know what routes do we need to rewrite/reroute ?
