### ISSUE TITLE
Your project will be ready in a few seconds

### ISSUE THREAD

**Issue by almaziphone** [teamhanko/hanko#1095]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

Your project will be ready in a few seconds. The project stops daily. Help what is the problem?

### Reproducing the bug

No access to the server. 503 Service Temporarily Unavailable

### Hanko Version

Release v0.8.4 · teamhanko/hanko

### OS Hanko Backend

None

### OS

None

### Environment

Other (e.g. Kubernetes)

**Comment by FlxMgdnz** [comment]
Can you please DM me in [our Discord](https://discord.com/channels/788396090180894730/1163042492678156370) so we can investigate the issue?

**Comment by orichcasperkevin** [comment]
am getting the same.. I am not running the backend on my machine, am using https://cloud.hanko.io/ .it has been over 15 minutes now
![Screenshot from 2023-10-23 10-17-34](https://github.com/teamhanko/hanko/assets/40789332/5b477b08-f28c-45f8-bbf9-b4febc227052)

**Comment by FlxMgdnz** [comment]
We had some issues with free nodes on our prod cluster. Should be solved now.
