### ISSUE TITLE
Fix Syntax Error in Code

### ISSUE THREAD

**Issue by varundhand** [teamhanko/hanko#1098]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

In the code, there is a syntax error that triggers a **console error** related to the `classList`. This issue impacts the functionality and user experience.

### Reproducing the bug

1. Open the [official website](https://www.hanko.io/) 
2. Open inspect tab and observe the console for the error message related to the _classList_

![Screenshot 2023-10-16 at 6 38 24 PM](https://github.com/teamhanko/hanko/assets/110025628/419980d0-9cba-443f-9f92-11aef74fc50e)

### Hanko Version

Release v0.8.4 · teamhanko/hanko

### OS Hanko Backend

None

### OS

macOS

### OS Version

14

### Browser Version

Chrome version 117.0.5938.149

### Environment

None

### Additional Context

I would like to work on this issue. Could you please assign it to me?

Additionally, could you please label this issue as `"hacktoberfest"` and `"hacktoberfest-accepted"`? Thank you!

**Comment by FlxMgdnz** [comment]
Thanks for reporting this @varundhand. We have to fix this in Webflow.
