### ISSUE TITLE
Add Scroll-to-Top Button for Improved User Experience

### ISSUE THREAD

**Issue by varundhand** [teamhanko/hanko#1106]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Description

This issue aims to enhance the user experience on the website by adding a scroll-to-top button. Currently, users have to manually scroll to the top of a page, which can be cumbersome, especially on longer pages. The addition of a scroll-to-top button will provide a convenient way for users to quickly return to the top of the page with a single click.

### Describe your ideal solution

The ideal solution for this issue is to implement a scroll-to-top button that appears when the user scrolls down a certain distance on a webpage. This button should be easily accessible, unobtrusive, and have a smooth scroll animation when clicked. It should significantly improve the website's usability.

### Hanko Version

Release v0.8.4 · teamhanko/hanko

### Additional Context

I'd like to work on this issue. Please assign it to me, and I'll be happy to contribute.
Additionally, kindly label this issue as `"hacktoberfest"` and `"hacktoberfest-accepted"`.

**Comment by FlxMgdnz** [comment]
Thanks for the suggestion. Our website is managed in Webflow, though. Closing this.
