### ISSUE TITLE
New event for signup, as onAuthFlowCompleted triggers for both sign-up/in

### ISSUE THREAD

**Issue by Ashutosh-Bhadauriya** [teamhanko/hanko#1158]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Description

New event for signup, as onAuthFlowCompleted triggers for both sign-up/in

### Workarounds or alternatives

We have to check if the user already exists for this

### Hanko Version

0.9.0

**Comment by FlxMgdnz** [comment]
@Ashutosh-Bhadauriya Please add a bit more context here

**Comment by Ashutosh-Bhadauriya** [comment]
As of now, we have a common event, `onAuthFlowCompleted` which triggers for both signup and signin. So, its hard to know when the new user signs up.  It will be good to have a separate event for signup. It was requested by a member on discord if I remember correctly

**Comment by FlxMgdnz** [comment]
Events were changed in a recent release, not relevant anymore.
