### ISSUE TITLE
Passcode to verify email is being sent as junk email in outlook

### ISSUE THREAD

**Issue by jcorriveau23** [teamhanko/hanko#1484]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

The passcode to verify user email is being sent as a junk email in outlook so my user struggle to create an account since they do not find the passcode in their email easily.

I am a free plan user and have recently integrated hanko cloud as authentification system really easily in my web app that I am currently building. https://hockeypool.live/en/login. The product is really good and easy to integrate. This issue is more of a question since there might be a reason to it so feel free to close the issue if it is not an issue :smile:.

### Reproducing the bug

1. Go to https://hockeypool.live/en/login
2. Register the account using an email
3. The passcode to verify the email is received as a junk email (users have trouble to find it)

### Hanko Version

API Version:  v0.11.0

### OS Hanko Backend

None

### OS

None

### Browser Version

all

### Environment

None

**Comment by FlxMgdnz** [comment]
Thanks for reporting this - although it is a potential problem with our cloud infrastructure and therefore not in the right place here.

**Comment by FlxMgdnz** [comment]
Please reach out on discord (https://www.hanko.io/community) or via email at support@hanko.io if you have any issues when using Hanko Cloud. It seems like there's currently a problem with your Hanko integration and we can definitely help there.
