### ISSUE TITLE
Not center alignment

### ISSUE THREAD

**Issue by jamesli2021** [teamhanko/hanko#1540]
### Checklist

- [X] #1544
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

Title and button not center alignment

### Reproducing the bug

No CSS was used, so the button appears too wide, and the title isn't centered.

![Screenshot 2024-07-31 at 12-00-24 Login to Member Account](https://github.com/user-attachments/assets/04ac6bae-3e7c-47cb-8655-4d0284787c57)

### Logs

```Shell
NA
```

### Configuration

```yml
NA
```

### Hanko Version

0.12

### OS Hanko Backend

macOS

### OS Version Hanko Backend

NA

### OS

None

### Environment

None

**Comment by FlxMgdnz** [comment]
Thanks @jamesli2021. Could you please explain what style you would expect or what you would like to achieve?

**Comment by jamesli2021** [comment]
I think it's fine, I was able to customise to my desire style except "Sign in or sign up" can be confusing for users who are new to this flow.

The best title we could change to "Sign in or create an account" and allow us to write our subtitle that can be personalise, brand story or personal touch to entice non-members to sign up. I hope to these improvements can really help you building great project!

**Comment by FlxMgdnz** [comment]
Thanks for your feedback. Glad that you were able to implement your design changes. You can change all strings with a custom translation: https://github.com/teamhanko/hanko/tree/main/frontend/elements#translations
