### ISSUE TITLE
Improving the UI for pricing page

### ISSUE THREAD

**Issue by swamimalode07** [teamhanko/hanko#1680]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Description

There is a huge gap between pricing content and navbar in pricing page

### Describe your ideal solution

changing the content placement for pricing page huge gap between pricing content and navbar in pricing page

### Hanko Version

v1.0.2

**Comment by subodhkangale07** [comment]
interesting issue

**Comment by DeviSriSaiCharan** [comment]
Hi @FlxMgdnz,

Can I contribute to this issue?

**Comment by FlxMgdnz** [comment]
Thanks for reporting, but the website is not part of this repository.
