### ISSUE TITLE
Bug Hunter : While profile overlay is opened navigating with back button does not close the profile overlay.

### ISSUE THREAD

**Issue by aritradevelops** [teamhanko/hanko#1684]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

When a user visits his profile page (overlay) navigating back does navigates the pages but as the overlay is there, he is not able to view the pages. It should close the profile overlay while user is trying to navigate back.

Points : 50 - 150

https://github.com/user-attachments/assets/0e097066-ce3d-46e8-93fd-d5e1683775cd

### Reproducing the bug

1. Open the profile page (overlay).
2. try to navigate back.

### Hanko Version

4120782c

### OS Hanko Backend

None

### OS

None

### Environment

None

**Comment by aritradevelops** [comment]
Hii, If this issue seems legitimate, I would like to work on this, and get some insights on where to find the profile component in the code base. If the issue is not relevant then you can close it. Thanks in advance!

**Comment by FlxMgdnz** [comment]
/award 100 Thanks for reporting the issue. It needs to be fixed in Hanko Cloud Console, which is not part of this repo.
