### ISSUE TITLE
Accessibility Advocate

### ISSUE THREAD

**Issue by DevGajjar28** [teamhanko/hanko#1714]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Description

while exploring a blog post on Hanko, on small devices blog post can be done more well-structured and aligned with another layout theme.

### Describe your ideal solution

so we can just align image to the center and make a sub-text to justify-center by this it can improve UI of blog page on one go.

## ** This is current Blog post UI: **
![image](https://github.com/user-attachments/assets/5e14faa0-a6d9-450a-a477-d57cb63dafcf)

## ** I would like to:**
![image](https://github.com/user-attachments/assets/9f66beb1-4111-4850-8025-49b1101026dd)

### Hanko Version

.

### Additional Context

I would like to resolve this under oss.gg and Hacktoberfest.

**Comment by FlxMgdnz** [comment]
/award 50 won't fix, it's the intended design :)
