### ISSUE TITLE
[🕹️] Quest Submisson: Meme Magic

### ISSUE THREAD

**Issue by Chirag8023** [teamhanko/hanko#1716]
### What side quest or challenge are you solving?

Meme Magic

### Points

150

### Provide proof that you've completed the task

[tweet](https://x.com/Chirag8023/status/1845702399517970771)

![Screenshot (26)](https://github.com/user-attachments/assets/3e77726a-e472-4b8b-a6de-bc35304213a0)

**Comment by vamus092** [comment]
Hi Chirag can you elaborate on the task to do in this challenge

**Comment by Chirag8023** [comment]
it's a oss.gg submission, create meme -> open new issue for submission.
