### ISSUE TITLE
[🕹️] Side quest: Follow Hanko on X

### ISSUE THREAD

**Issue by Sa1-Codes** [teamhanko/hanko#1723]
### What side quest or challenge are you solving?

follow hanko on X

### Points

50

### Description

followed hanko on X, liked and commented hackathon post

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/81b74883-93f5-4582-b1e4-744f1f479a0a)

![image](https://github.com/user-attachments/assets/c91fae94-21ea-42e1-8106-b2b99aff1d88)

**Comment by Rajan3208** [comment]
![Screenshot 2024-10-14 201011](https://github.com/user-attachments/assets/2f1d77fc-6376-464b-9fbe-036a753f0e6a)
![Screenshot 2024-10-14 201028](https://github.com/user-attachments/assets/3ecae824-b679-44fa-9f1d-7d01d00a7a9c)
