### ISSUE TITLE
[🕹️] Following Hanko's LinkedIn Page

### ISSUE THREAD

**Issue by shreykx** [teamhanko/hanko#1724]
### What side quest or challenge are you solving?

**To FOLLOW HANKO's LinkedIn Page.**

### Points

50

### Description

I followed **Hanko**'s LinkedIn page.

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/8e88f06f-ee53-49c3-ac87-d710ab5b7c14)

**Comment by Rajan3208** [comment]
![Screenshot 2024-10-14 201441](https://github.com/user-attachments/assets/8503bac3-9a3c-4738-9546-3f67fa410325)
