### ISSUE TITLE
[🕹️]   Technical article covering authentication, passkeys

### ISSUE THREAD

**Issue by naaa760** [teamhanko/hanko#1744]
### What side quest or challenge are you solving?

Technical article covering authentication, passkeys

### Points

750

### Description

https://nehaprasad27118.medium.com/exploring-authentication-with-passkeys-a-new-frontier-in-secure-login-005a65764afe

### Provide proof that you've completed the task

![Screenshot from 2024-10-15 12-51-18](https://github.com/user-attachments/assets/19fd9b42-e4b3-426c-94c3-6953e52315b4)

**Comment by Shivam1-123** [comment]
what is the task?
