### ISSUE TITLE
[🕹️]Follow Hanko X Page- Side Quest

### ISSUE THREAD

**Issue by sahiladit** [teamhanko/hanko#1757]
### What side quest or challenge are you solving?

Follow Hanko X Page- Side Quest

### Points

50

### Provide proof that you've completed the task

<img width="1440" alt="Screenshot 2024-10-15 at 8 12 19 PM" src="https://github.com/user-attachments/assets/fd4a66a5-4ea4-4af7-8c56-639e0047a07c">

**Comment by programmerftw** [comment]
<img width="1440" alt="Screenshot 2024-10-16 at 04 28 04" src="https://github.com/user-attachments/assets/e88a4f1b-3d89-4474-ab98-2d285fa01124">
Completed following Hanko X page!
Issue  #1757
