### ISSUE TITLE
[🕹️]Follow Hanko on X

### ISSUE THREAD

**Issue by rajeevDewangan** [teamhanko/hanko#1761]
### What side quest or challenge are you solving?

Follow Hanko on X

### Points

50

### Description

Following Hanko on X

### Provide proof that you've completed the task

![Screenshot 2024-10-15 203730](https://github.com/user-attachments/assets/c5aeb047-8147-4b00-956d-548a3d748b4d)

**Comment by Gdhoundiyal** [comment]
What side quest or challenge are you solving?
Follow Hanko on X

Points
50

Description
Following Hanko on X

Provide proof that you've completed the task
![image](https://github.com/user-attachments/assets/b2720148-c039-4a96-89ff-a7a1bc574e1b)

**Comment by Ravi3727** [comment]
![follow](https://github.com/user-attachments/assets/252f3659-8aa2-4dca-aaa5-adf0a0889251)
I followed the Hanko on X.com
