### ISSUE TITLE
[🕹️]Follow Hanko LinkedIn Page #1764

### ISSUE THREAD

**Issue by HighRatedMayank** [teamhanko/hanko#1765]
### What side quest or challenge are you solving?

Follow Hanko on LinkedIn Page.

### Points

50

### Description

Followed Hanko on LinkedIn Page.

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/a0be1d68-5a39-4f69-aacc-a78e804d593a)

**Comment by ShaniPratapSingh** [comment]
you can check it on my linkdin proflie :" www.linkedin.com/in/shani-pratap-singh-734098299 "

**Comment by ShaniPratapSingh** [comment]
@oss-gg done

**Comment by ShaniPratapSingh** [comment]
my task has been done of follow the hanko as i mentioned above my linkdin profile you can check it
