### ISSUE TITLE
[🕹️] Starry-eyed supporter

### ISSUE THREAD

**Issue by Khaan25** [teamhanko/hanko#1768]
### What side quest or challenge are you solving?

Starry-eyed supporter

### Points

150

### Provide proof that you've completed the task

![WhatsApp Image 2024-10-15 at 11 40 27_64fa213f](https://github.com/user-attachments/assets/e164dd88-095e-435e-bc62-b629a9c46207)
![WhatsApp Image 2024-10-15 at 11 43 45_ad7fa0da](https://github.com/user-attachments/assets/820681a8-c165-45b1-a60d-6d2e205d7dbd)
![WhatsApp Image 2024-10-15 at 11 45 44_52509b1f](https://github.com/user-attachments/assets/11d9114e-032b-45a9-9cf8-652a573359c3)
![WhatsApp Image 2024-10-15 at 11 49 22_05a38b9a](https://github.com/user-attachments/assets/b5361750-c69b-4aee-b946-20633858b53e)
![WhatsApp Image 2024-10-15 at 16 44 14_912efd4b](https://github.com/user-attachments/assets/26d3bfc6-bdc0-47d4-b299-6545cadb623c)

**Comment by Shivam1-123** [comment]
Does this task really providing points? 
Because I have done a few and there is no point showing on my profile

**Comment by jobenjada** [comment]
removed these points in case we let him participate in the raffle
