### ISSUE TITLE
[🕹️] Side Quest: Follow Hanko on X (Twitter)

### ISSUE THREAD

**Issue by AmanPathan** [teamhanko/hanko#1786]
### What side quest or challenge are you solving?

Follow Hanko on X (Twitter)

### Points

50

### Description

here is the proof that I am following Hanko's account on twitter

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/66af6a45-4aec-45be-bffc-f5074d818a9a)

**Comment by Nayakyash005** [comment]
What side quest or challenge are you solving?
Follow Hanko on X (Twitter)

Points
50

Proof that i followed hanko on x is 
![Screenshot 2024-10-17 151738](https://github.com/user-attachments/assets/adc63cf5-82f6-404d-b584-422dcf7344e5)
