### ISSUE TITLE
[🕹️]Technical article covering authentication, passkeys

### ISSUE THREAD

**Issue by sahiladit** [teamhanko/hanko#1791]
### What side quest or challenge are you solving?

What side quest or challenge are you solving?
Technical article covering authentication, passkeys

### Points

750

### Description

Link of the article : https://medium.com/@sahiladit/passkeys-a-secure-and-convenient-future-beyond-passwords-e557f75222d1

### Provide proof that you've completed the task

<img width="1440" alt="Screenshot 2024-10-17 at 5 14 11 PM" src="https://github.com/user-attachments/assets/6bd4b035-63bc-4d60-8346-697f76ad039e">

**Comment by lostinvsc** [comment]
explain little bit more about this issue

**Comment by sahiladit** [comment]
This is not an issue,it's an article related to passkeys.
