### ISSUE TITLE
[🕹️] Side Quest: Follow Hanko on LinkedIn

### ISSUE THREAD

**Issue by Yashwanth-Chandrakumar** [teamhanko/hanko#1794]
### What side quest or challenge are you solving?

Follow Hanko on LinkedIn

### Points

50

### Description

Follow Hanko on LinkedIn

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/cf2f8ee1-aa07-4ab5-8871-cc9b266866e2)

**Comment by Mstr-Creta** [comment]
🔑

**Comment by Mstr-Creta** [comment]
![Screenshot 2024-10-17 204807](https://github.com/user-attachments/assets/aa48dcf4-fc96-4b71-a5ba-0cc5c99b148c)

**Comment by Yashwanth-Chandrakumar** [comment]
🔑
