### ISSUE TITLE
[🕹️] Follow Hanko on X

### ISSUE THREAD

**Issue by Asymtode712** [teamhanko/hanko#1801]
### What side quest or challenge are you solving?

[🕹️] Follow Hanko on X

### Points

50

### Provide proof that you've completed the task

![twitter](https://github.com/user-attachments/assets/dccbe1c2-f46c-4506-80f9-686aabec107c)

**Comment by kaif969** [comment]
![Screenshot 2024-10-18 010240](https://github.com/user-attachments/assets/a29413fc-e5c4-4710-9729-c2ff03b6ca39)

**Comment by VigneshWorkcrew** [comment]
![image](https://github.com/user-attachments/assets/117474c7-5694-466a-81ca-27ffba36482e)

Completed
