### ISSUE TITLE
[🕹️] Follow Hanko.io on twitter - SideQuest

### ISSUE THREAD

**Issue by techwizard31** [teamhanko/hanko#1808]
### What side quest or challenge are you solving?

I followed Hanko.io on twitter

### Points

50

### Provide proof that you've completed the task

![Screenshot (53)](https://github.com/user-attachments/assets/fdfbafb7-93f6-4f5c-ad84-bb141c21bac6)

**Comment by sureshjangid** [comment]
### What side quest or challenge are you solving?
I followed Hanko.io on twitter

### Points
50

### Description
I followed Hanko.io on twitter

### Provide proof that you've completed the task
![image](https://github.com/user-attachments/assets/0adbc886-8bdc-43ef-8cb0-fdedfe58ddb6)
