### ISSUE TITLE
[🕹️] Follow hanko.io on linkedIn

### ISSUE THREAD

**Issue by techwizard31** [teamhanko/hanko#1809]
### What side quest or challenge are you solving?

I followed hanko.io on linkedin

### Points

50

### Provide proof that you've completed the task

![Screenshot (54)](https://github.com/user-attachments/assets/4f3272b8-9e8e-4156-8c5e-70731375a7a8)

**Comment by sureshjangid** [comment]
### What side quest or challenge are you solving?
I followed hanko.io on linkedin

### Points
50

Description
I followed hanko.io on linkedin

### Provide proof that you've completed the task
![image](https://github.com/user-attachments/assets/3034d36d-7db0-4a22-adc8-137c4291a66b)
