### ISSUE TITLE
[🕹️] Starry-eyed supporter

### ISSUE THREAD

**Issue by shivamkumarsingh28** [teamhanko/hanko#1817]
### What side quest or challenge are you solving?

 the same side quest called “Starry-eyed supporter”

### Points

Get 5 friends to star these repositories and get 150 points per repository - done!

### Description

hey hey! 

you look gorgeous today.

so my laptop is kinda old and you can help me get a MacBook with 1 minute of your time :)

just head over to these 5 repositories, star them and send me a screenshot that you did:

- **Formbricks**: https://github.com/formbricks/formbricks
- **Hanko**: https://github.com/teamhanko/hanko
- **OpenBB Finance**: https://github.com/OpenBB-finance/OpenBB
- **Papermark**: https://github.com/mfts/papermark
- **Unkey**: [https://github.com/unkeyed/unkey](https://github.com/unkey/unkey)

thank you sooo much!
(if you’re curious how this gets me a mac, i’m taking part in the [[oss.gg](http://oss.gg/)](http://oss.gg) hackathon 🕹️)

### Provide proof that you've completed the task

![saeeam](https://github.com/user-attachments/assets/a04462f2-ca9d-4ce1-a62c-e78da026a5a8)
![satyam kumar](https://github.com/user-attachments/assets/052176fd-87f2-4a64-a98c-4fc622db4116)
![satyashil sharma](https://github.com/user-attachments/assets/bf17eeac-dceb-4a70-b9d4-e28ee5018634)
![shivam singh](https://github.com/user-attachments/assets/7dc97d6d-b563-404a-9a44-bec848536b59)
![sundram kumar](https://github.com/user-attachments/assets/9f764696-3adb-44d6-a99b-caf93246de4c)

**Comment by FlxMgdnz** [comment]
Awarded in another issue
