### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by 1fexd** [teamhanko/hanko#1824]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Description

On your landing page you claim to be "[...] fully open source.", which contradicts the [license](https://github.com/teamhanko/hanko/blob/main/backend/ee/LICENSE) present in the `backend/ee` directory

### Describe your ideal solution

Your landing page should not claim that Hanko is "fully open source"

### Hanko Version

latest

**Comment by FlxMgdnz** [comment]
The /ee code is still open source.

**Comment by 1fexd** [comment]
It is quite literally not. The source being available does not make it open source.

**Comment by jmls** [comment]
also contradicts the readme

Licenses
[hanko-elements] (https://github.com/teamhanko/hanko/blob/main/frontend/elements) and 
[hanko-frontend-sdk](https://github.com/teamhanko/hanko/blob/main/frontend/frontend-sdk)

 are licensed under the [MIT License](https://github.com/teamhanko/hanko/blob/main/frontend/elements/LICENSE). 

**_Everything else_**  (emphasis mine)

in this repository, including [hanko backend](https://github.com/teamhanko/hanko/blob/main/backend), is licensed under the [AGPL-3.0](https://github.com/teamhanko/hanko/blob/main/LICENSE).

so is "ee" (which is under the backend folder) AGPL 3.0 ?

**Comment by FlxMgdnz** [comment]
We will be removing the /ee license soon. Earlier plans were to add more features there that are only needed if you want to host Hanko in a similar way as we do with Hanko Cloud, but so far that hasn't been necessary and we don't think it's worth keeping the /ee license just for the SAML code.

**Comment by jmls** [comment]
that's great news ! Thanks
