### ISSUE TITLE
[🕹️]Technical article covering authentication, passkeys, etc. (300-1500 Points) 

### ISSUE THREAD

**Issue by AshishViradiya153** [teamhanko/hanko#1858]
### What side quest or challenge are you solving?

Technical article covering authentication, passkeys, etc.

[medium article](https://medium.com/@ashishviradiya153/passkeys-the-future-of-authentication-and-passwordless-login-39a563ec793a)

### Points

?

### Provide proof that you've completed the task

article

**Comment by Khaan25** [comment]
Seems like duplicate of my issue #1839

**Comment by AshishViradiya153** [comment]
@Khaan25 double check everything, everyone can create blog ...
