### ISSUE TITLE
[🕹️]Technical article covering authentication, passkeys, etc.:

### ISSUE THREAD

**Issue by shivamkumarsingh28** [teamhanko/hanko#1937]
### What side quest or challenge are you solving?

Write a technical article that can be posted on our blog (naming you as guest author), e.g.
- Advantages and disadvantages of building a login that uses only passkeys
- How passkey autofill (Conditional UI) works
- Making passwords optional - what’s important when users can delete their passwords?
- Using passkeys as a password replacement vs. for MFA
Just as a general direction for the content. Most of the above can be tried out with different Hanko configurations (MFA coming in Oct). We’re happy to see many other ideas as well.

### Points

(300-1500 Points)

### Description

https://dev.to/shivam_kumar_singh/implementing-secure-hanko-authentication-password-and-passkey-based-login-registration-and-logout-in-any-tech-stack-59ph

PR: Done 
https://github.com/shivamkumarsingh28/hanko/pull/2

### Provide proof that you've completed the task

![Screenshot 2024-10-30 171314](https://github.com/user-attachments/assets/76806925-f452-4da7-95e8-5d5e3907c42a)

**Comment by FlxMgdnz** [comment]
/award 100 Thanks. Unfortunately, the blog post doesn't really contain any meaningful coherent content, so I can't give it a higher score.
