### ISSUE TITLE
[🕹️]Use Hanko in your app and write a blog post about it:

### ISSUE THREAD

**Issue by shivamkumarsingh28** [teamhanko/hanko#1938]
### What side quest or challenge are you solving?

Use Hanko API and Elements as auth provider in your application. Then write a technical blog post about the process and outcome, including code snippets and a link back to [hanko.io](http://hanko.io/).

### Points

(1500 Points)

### Description

Technical writting to instruct how to setup hanko auth with nextjs for authentication 
https://dev.to/shivam_kumar_singh/seamless-authentication-in-nextjs-with-hanko-implementing-passwordless-login-passkeys-and-multi-factor-authentication-5272

source code 
Hanko auth with nextjs project
https://github.com/shivamkumarsingh28/hanko_auth_nextjs_project

PR Done
https://github.com/shivamkumarsingh28/hanko/pull/3

### Provide proof that you've completed the task

![Screenshot 2024-10-27 173641](https://github.com/user-attachments/assets/067574ff-03a3-4e75-9517-d412d9c3bdd5)
![Screenshot 2024-10-27 173833](https://github.com/user-attachments/assets/ffe2cccd-3e00-46c0-9e9a-05b6a7144ff1)
![Screenshot 2024-10-27 173858](https://github.com/user-attachments/assets/064747f6-463d-4154-a2cf-872bd5c93dc5)
![Screenshot 2024-10-27 173909](https://github.com/user-attachments/assets/95d180ce-949f-4f65-9fcd-510d3805ea07)
![Screenshot 2024-10-27 174902](https://github.com/user-attachments/assets/50371dba-d227-4ca7-b217-c6ad2d0c5a27)
![Screenshot 2024-10-27 174937](https://github.com/user-attachments/assets/328548bc-1da8-445e-8cd0-b9e75a5265f3)
![Screenshot 2024-10-27 174952](https://github.com/user-attachments/assets/3e783abb-4ce9-46bd-ac2b-dd6161e7c09e)
![Screenshot 2024-10-27 175051](https://github.com/user-attachments/assets/fcf40f64-f59d-4243-927e-ed94d81e2073)
![Screenshot 2024-10-27 175115](https://github.com/user-attachments/assets/fd6444d4-718f-4a9a-85eb-a940e0e10791)
![Screenshot 2024-10-27 175126](https://github.com/user-attachments/assets/6ee05322-5162-436c-bab5-1074f54216c2)
![Screenshot 2024-10-27 175136](https://github.com/user-attachments/assets/52eb55ef-dea6-47de-989c-c3de4145a96d)
![Screenshot 2024-10-27 190212](https://github.com/user-attachments/assets/f2bf7689-faf9-4162-b33d-ca301a5872a1)
![Screenshot 2024-10-27 190221](https://github.com/user-attachments/assets/7ca68016-20d3-43c6-8717-61c4a4d65462)
![Screenshot 2024-10-27 190248](https://github.com/user-attachments/assets/db2fa3b1-862a-4075-9dbd-e4dfef07c392)
![Screenshot 2024-10-27 190305](https://github.com/user-attachments/assets/3e819950-3641-474b-ba53-7d839cfb6cbb)
![Screenshot 2024-10-27 190330](https://github.com/user-attachments/assets/66a8b296-32d9-4e3a-9936-8832bd058c67)
![Screenshot 2024-10-27 190348](https://github.com/user-attachments/assets/2e7d59e4-fb3a-4896-91c5-ba779f030d6b)
![Screenshot 2024-10-27 190425](https://github.com/user-attachments/assets/ae568e39-79c1-4a22-8925-603dc7330d23)
![Screenshot 2024-10-27 191046](https://github.com/user-attachments/assets/d88a7ba1-c550-4b06-af9d-3ffd88704b9c)
![Screenshot 2024-10-27 191429](https://github.com/user-attachments/assets/3b816ffc-917c-4422-8f07-a277d2324049)
![Screenshot 2024-10-27 191437](https://github.com/user-attachments/assets/3a613a88-50f0-4f35-9694-bb48a7002c04)
![Screenshot 2024-10-27 191447](https://github.com/user-attachments/assets/192b2b9a-91d0-4554-8377-25bd9cab93a1)
![Screenshot 2024-10-27 191505](https://github.com/user-attachments/assets/81585d72-6cf7-4ea0-a1bb-3cdb0cce981a)
![Screenshot 2024-10-27 191514](https://github.com/user-attachments/assets/ba6c63c7-e267-49d9-8359-8ece7f4362dc)
![Screenshot 2024-10-27 191526](https://github.com/user-attachments/assets/d33b8f58-2d74-4a37-b32e-6235c5c97685)
![Screenshot 2024-10-27 191543](https://github.com/user-attachments/assets/d2b34526-a8bd-428b-a0f6-563eb15da42a)
![Screenshot 2024-10-27 191606](https://github.com/user-attachments/assets/d04879fb-183d-4e4b-9664-06f223ed37be)

**Comment by FlxMgdnz** [comment]
/award 750 I'm awarding 50% of the points for this challenge because the blogpost has more resemblance to a screenshot gallery than an article - but thanks anyway
