### ISSUE TITLE
[🕹️]Test drive Hanko

### ISSUE THREAD

**Issue by shivamkumarsingh28** [teamhanko/hanko#1939]
### What side quest or challenge are you solving?

Record yourself (Screenstudio, Loom, Cap.so…) while you visit [hanko.io](http://hanko.io/) and start your journey from there. You don’t need to show your face but voice is required. Ideally, try building an app with a tech stack of your choice and use Hanko for authentication, integrate Hanko Elements and implement the steps necessary for auth, e.g. logout and JWT validation. If you can’t make it that far that’s also fine. Even your experience simply trying to understand what Hanko is and how it works will already be valuable to us. Share your honest thoughts while doing so. We love to hear your opinions, good or bad. Make sure to point out if you struggle with anything so we can improve. Upload the clip to YouTube, Loom, Google Drive… and put the video link into the PR. If you want to share other feedback that is not in the video please add it to the PR as well.

### Points

(250-750 Points)

### Description

I done this test drive hanko auth 

PR Done 👍 
https://github.com/shivamkumarsingh28/hanko/pull/4

### Provide proof that you've completed the task

https://drive.google.com/file/d/1NLbbPOpNyV0NthS98Kp1DlSx6Kt-hCr7/view?usp=sharing

**Comment by FlxMgdnz** [comment]
/award 250 Thanks @shivamkumarsingh28! Good overview. Would have loved if you'd included your journey building the actual app with Hanko, and perhaps some feedback or things you did not understand immediately.
