### ISSUE TITLE
[🕹️]Starry-eyed Supporter (150 Points): 

### ISSUE THREAD

**Issue by sumit2011** [teamhanko/hanko#1942]
### What side quest or challenge are you solving?

star the repo

### Points

150 Points

### Description

stared Hanko repo

### Provide proof that you've completed the task

![1](https://github.com/user-attachments/assets/ecc12838-43c0-42f4-b9c6-9abd8a3f83c4)
![2](https://github.com/user-attachments/assets/f641b96d-ab54-4e20-bf3d-03f2449b874d)
![3](https://github.com/user-attachments/assets/47f68143-0745-4c60-a0a2-7ad9ba32486a)
![4](https://github.com/user-attachments/assets/e7e2663a-02c4-48b1-871c-594967483e83)
![5](https://github.com/user-attachments/assets/fbdebd27-a258-45d0-89cd-779d0668223f)

**Comment by Shrinivasdumbali** [comment]
![1](https://github.com/user-attachments/assets/f9bbaac4-0b3d-494f-9401-a93d54e4923a)
![2](https://github.com/user-attachments/assets/04fd1ab6-157d-4f2c-a128-94c7f2f8e0ca)
![3](https://github.com/user-attachments/assets/5919a921-32cc-4a1a-973b-d8b178dc56a0)
![4](https://github.com/user-attachments/assets/148df006-6436-44e3-bd06-d793bfd42307)
![5](https://github.com/user-attachments/assets/d9d763dd-dc08-4ad2-b776-049b6841ced8)

side quest completion!
