### ISSUE TITLE
OIDC endpoint: .well-known/openid-configuration

### ISSUE THREAD

**Issue by half2me** [teamhanko/hanko#1958]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Description

I would like to use Hanko with AWS AppSync. AppSync supports OpenID Connect.
https://docs.aws.amazon.com/appsync/latest/devguide/security-authz.html#openid-connect-authorization
I couldn't find any way to get the required: `.well-known/openid-configuration` url from Hanko. Looking at the oidc specification, it seems like this would just be a json document listing the configuration and jwks url etc. I can see the jwks url on the dashboard, so I'm thinking it might be possible to have this url available too?

### Describe your ideal solution

The dashboard to have a link to a `.well-known/openid-configuration` url that I can use to connect it to AWS AppSync

### Workarounds or alternatives

I'm considering create this page myself and populating it with the details of my hanko jwks url.

### Hanko Version

latest

### Additional Context

I've looked at #782 and #1320 but I think these are referring to using an external provider with Hanko. In my case I need the opposite. I need the oidc parameters for Hanko itself.

**Comment by FreddyDevelop** [comment]
@half2me Hanko is **not** a oidc or oauth2 provider. So currently you can not use Hanko with AWS AppSync, unfortunately.
