### ISSUE TITLE
Rate limiting (application layer)

### ISSUE THREAD

**Issue by FreddyDevelop** [teamhanko/hanko#24]
Currently we don't have a backoff strategy for passwords and passcodes, but we should implement one.

### Proposal:

**Passwords:**
After 3 "free" tries the backoff takes over. (exponential or linear should be discussed)
Why "free" tries, because sometimes a user types in the wrong password, but immediately remembers and types in the correct one, when the user must wait then, he will be annoyed.

**Passcodes:**
Each passcode has 3 tries to be entered correctly. After that a new passcode must be requested. 
Requesting the second (third?) passcodes will trigger the backoff strategy.

**Comment by FlxMgdnz** [comment]
I'd vote to allow for 5 password attempts until the backoff kicks in. After that, we can begin the backoff with a timespan that makes sense, like 10s or so - i.e. I don't think starting with something like 1s makes sense UI wise.

**Comment by FlxMgdnz** [comment]
We discussed this internally and came up with the following draft:

- Built rate limiting on application layer
- Limit implementation to cases where IP address **and** user identifier can be checked (other cases must be handled on network layer)
- Chose user-friendly backoff algorithm (see comment above)
- Rate limited cases:
    - password input
    - passcode email sending
    - forgot password email sending
    - ~~passcode input~~ (backoff already in place)
    - more??
- Show backoff timer in frontend when active (→ backend must provide backoff time)
- Don’t forget to document approach in backend (+ frontend??) readme
