### ISSUE TITLE
Return same HTTP Code for both passcode ID not found and passcode is incorrect

### ISSUE THREAD

**Issue by irby** [teamhanko/hanko#240]
Currently, the backend returns an HTTP 404 NotFound if the [passcode ID supplied in the request cannot be found](https://github.com/teamhanko/hanko/blob/main/backend/handler/passcode.go#L164) and returns an HTTP 401 Unauthorized response if the [passcode ID is correct but the code supplied is not](https://github.com/teamhanko/hanko/blob/main/backend/handler/passcode.go#L192). Most standard login forms return the same HTTP code (401) if either username or password are incorrect, and since passcodes essentially act as a username/password combination I suggest we return the same HTTP code for either scenario.

Thinking from an adversary's standpoint, letting them know whether a passcode ID exists helps them when brute forcing a bunch of passcode ID and passcode options.

**Comment by aspeteRakete** [comment]
Hey Matthew,
thanks for your contribution. 
You are right, returning a 404 in this case goes in the direction of an account enumeration.

Just checking in on @bjoern-m: Does the hanko-element have differentiated logic implemented in this case?
If not I would implement Matthews suggestion.
