### ISSUE TITLE
Frontend seems to expect 10-character passwords, regardless of backend config

### ISSUE THREAD

**Issue by FlxMgdnz** [teamhanko/hanko#273]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

With passwords enabled, but no min length set, the frontend shows a min length requirement of 10 characters for a new password. The default value of the backend is 8 characters, thought. It seems like the frontend is not in sync with the backend setting.

### Reproducing the bug

1. Enable passwords, but set no min length requirement
2. Create a new account through the UI
3. On the view to set a password, the min length requirement of 10 characters is enforced

### Configuration

```yml
passwords:
  enable: true
```

### Hanko Version

0.2.0

**Comment by bjoern-m** [comment]
Has been solved in https://github.com/teamhanko/hanko/pull/495.
