### ISSUE TITLE
First attempt passkey setup fails on iPhone

### ISSUE THREAD

**Issue by swimmingninja** [teamhanko/hanko#319]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

When creating a passkey on iPhone the passkey will not save correctly on first attempt.

Note: this test was done on www.passkeys.io

### Reproducing the bug

When creating a passkey on iPhone the passkey will not save correctly on first attempt. The iPhone UI states that the Passkey has been saved however the Hanko login window appears to just time out. Tapping “Set up a passkey” again will correctly set up the passkey. 

Note: this test was done on www.passkeys.io

### Hanko Version

Unsure (most current version used on passkeys.io on October 20, 2022)

**Comment by FlxMgdnz** [comment]
Unfortunately, this seems to be a bug in Safari when using Conditional UI. We've already invested a lot of time to solve this problem on our side, but so far without success.

See also:
- https://blog.millerti.me/2022/10/12/apple-passkeys-out-in-the-wild/#ios-1
- https://twitter.com/IAmKale/status/1576801941291614210
