### ISSUE TITLE
passkeys.io: Timeout when signing in with Chrome after account setup on iOS

### ISSUE THREAD

**Issue by DePasqualeOrg** [teamhanko/hanko#335]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

I created an account on my iPhone and then tried to sign in on Chrome on macOS. I selected "Use phone with a QR code", scanned the code with my iPhone, and selected "Sign in with a Passkey" on my iPhone, but then the sign-in process just timed out. Bluetooth and WiFi are enabled on both devices.

### Reproducing the bug

See above

### Hanko Version

None

**Comment by DePasqualeOrg** [comment]
I did it as quickly as possible (scanned the QR code and selected "Sign in with a Passkey" on the iPhone about 1 second after it appeared in Chrome on macOS), but I get the same result. My iPhone is stuck in "Connecting …", and Chrome times out with an error after about a minute.

**Comment by FlxMgdnz** [comment]
Thank you. It is most probably an issue we cannot influence then. But let me try to reproduce this on our test devices and see what can be done about it.

**Comment by FlxMgdnz** [comment]
Seems like a Bluetooth connection issue.
