### ISSUE TITLE
elements: registration confirmation page not wrapping paragraph content per default

### ISSUE THREAD

**Issue by lfleischmann** [teamhanko/hanko#338]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

Really long user emails are not wrapped per default on the registration confirmation page paragraph message informing the user, that no account for the given email address exists (see screenshot in 'Additional context' below).

### Reproducing the bug

1. Run the [quickstart](https://github.com/teamhanko/hanko#quickstart)
2. In your browser, navigate to `http://localhost:8888`
3. On the `LoginEmail` page (`Sign in or sign up`) enter an (obnoxiously) long email 
4. Click `continue`

### Hanko Version

558caebb1f98a8b2e24e19978915afb99fb53888

### OS

macOS

### OS Version

macOS Monterey 12.6

### Browser Version

All browsers, all versions (I guess?)

### Environment

Docker Compose

### Additional Context

Tested with the quickstart, the problem seems to be present on all browsers regardless of the run environment though.

<img width="1705" alt="Registration_Confirmation_Unwrapped_Content" src="https://user-images.githubusercontent.com/67686424/198094753-84d979df-f9c5-4047-9db6-8f87b9fbbe03.png">

**Comment by bjoern-m** [comment]
Has been solved in https://github.com/teamhanko/hanko/pull/495, hence I close this ticket.
