### ISSUE TITLE
Could not able to click Create PassKey button- ( Mozilla,Ubuntu 22.04.1 LTS)

### ISSUE THREAD

**Issue by rainfall-datta** [teamhanko/hanko#351]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

After giving login to 8888 port , I got pass key after adding passkey i landed to My Profile but "Create a PassKey" Button at right is disable,
On Mouse over showing " Web Authn is not supporting to this browser"

![image](https://user-images.githubusercontent.com/30334639/200099770-272302de-3e86-415f-93f9-0c319d504cfe.png)

Could not able to "Create Pass Key" - ( Mozilla, Ubuntu-20.04 LTS)

### Reproducing the bug

git clone https://github.com/teamhanko/hanko.git
Then, in the newly created hanko folder, just run:

docker compose -f deploy/docker-compose/quickstart.yaml -p "hanko-quickstart" up --build

### Hanko Version

HANKO-Beta 0.3.0

### OS

Other

### OS Version

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04

### Browser Version

FireFox - 106.0.4

### Environment

Docker Compose

**Comment by rakesh-rainfall** [comment]
Hanko Team, Just as side note we have tried installing the Hanko on local Windows 11 system and accessing the same using Chrome browser, it worked fine. 

Our suspicion is hosting on Ubuntu is causing it.. but we are not sure...

**Comment by FlxMgdnz** [comment]
Unfortunately, multi-device/synced passkeys are not yet supported on Ubuntu. 

As soon as we ship #331, it should at least be possible with Ubuntu/Firefox to create single-device passkeys on physical Security Keys.

**Comment by rakesh-rainfall** [comment]
@FlxMgdnz 
Thanks for response...

As per your comment, looks like the hosting on ubunto is causing it, is that correct?

Just to confirm and get clear understanding. I am wondering why or for what hanko depends on any server side component for webauthn? 

Also can you point us to any doc that gives supported platforms?

Any insights will be helpful to us to plan future strategy...

**Comment by FlxMgdnz** [comment]
Hosting on Ubuntu should not be a problem at all, there are no specific requirements on the server side.

Creating a passkey requires WebAuthn to be available on the client side, though. In your case, you can host Hanko on Ubuntu, but passkeys would only be usable on non-Ubuntu clients.

**Comment by rakesh-rainfall** [comment]
Yes that makes sense. However we are puzzled because the pass key button is disabled when we host it on Ubuntu and try to access using windows client using Chrome. 

This works perfectly fine when hosted on windows locally and accessed using local client.

Any idea why this would happen?

**Comment by FreddyDevelop** [comment]
Did you serve the `hanko-quickstart` over `https` while hosting it on Ubuntu? 

The Web Authentication API only works in a secure context which is either `localhost` or `https`. If you want to host the `hanko-quickstart` on a different machine you must serve it over `https` to be able to use passkeys.

**Comment by DattaAdsule** [comment]
Yes we have hosted that on Https and tried but internally quick start and element containers communicate over http, so it was giving secure protocol issue over hanko element container access

**Comment by rakesh-rainfall** [comment]
Hi Hanko Team,
Do you have any reference docker-compose file for https setup?

**Comment by FlxMgdnz** [comment]
Closing this for now. Please reach out if you have any more issues.
