### ISSUE TITLE
Dead link in documentation

### ISSUE THREAD

**Issue by salieflewis** [teamhanko/hanko#383]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

Following the React + Hanko guide here https://docs.hanko.io/guides/react

This link 404s https://github.com/teamhanko/hanko/blob/main/elements/README.md#script

### Reproducing the bug

Click the above link

### Hanko Version

n/a

**Comment by FlxMgdnz** [comment]
Thanks! We recently restructured the repo a bit. #380 will fix the issue.

**Comment by salieflewis** [comment]
Of course. Also, where can I go to obtain an API key?

Best,
Salief
