### ISSUE TITLE
hanko-auth: username input label background buggy on dark themes

### ISSUE THREAD

**Issue by FlxMgdnz** [teamhanko/hanko#389]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

The username input label looks buggy on dark themes when the input becomes disabled.

![image](https://user-images.githubusercontent.com/20115649/202190948-a18c80fa-2ae6-4e8a-9d72-7edc192f811b.png)

### Reproducing the bug

1. Click "Sign in with a passkey"
2. See result

### Hanko Version

0.3.0

**Comment by bjoern-m** [comment]
When the component's background color and the input field's background color differs, the label will look that way. We need to set a background color for the label, otherwise the border of the input would be visible behind the label. As an alternative we could place the labels above the inputs.

**Comment by FlxMgdnz** [comment]
I think we should change the labels from floating to regular labels that sit above the inputs for better flexibility with background colors.

**Comment by bjoern-m** [comment]
Agree. Let's wait for @mialenakneschke's feedback. I played around with it, but unsure how it'll work out in any situation. To example, when the input's border radius gets increased, the label should move either further to the right or stay on a fixed position on the left.

**Comment by FlxMgdnz** [comment]
Fixed with latest merge #495
