### ISSUE TITLE
Passkeys.io contradicts itself

### ISSUE THREAD

**Issue by plattrap** [teamhanko/hanko#400]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

Cannot use the demo without a valid email address entered (or 1:1,000,000 guess)!

```

Create an account with a passkey
1. Enter your email address* and hit Continue.
‍
2. Follow the prompts to create an account and a passkey.
‍
* You can use a fake email address, but then you won't be able to access the account without the passkey. If you want to create multiple accounts, you can just add +n to your email address, e.g., max+2@hanko.io
```

### Reproducing the bug

1) Go to https://www.passkeys.io/
2) Enter dummy email address
3) Cannot create credentials.

### Hanko Version

33355eb3-9429-4a18-8dfe-f17f7e86300b-js.hanko.io

**Comment by like-a-bause** [comment]
"You can use a fake email address (IF your device supports passkeys)." Would be the precise statement.
Your device does no seem to support passkeys and in that case passkeys.io is falling back to an email sent passcode.
Would you be so kind to fill in the missing information in the bug report?
