### ISSUE TITLE
Support `DATABASE_URL` environment variable

### ISSUE THREAD

**Issue by IgnisDa** [teamhanko/hanko#438]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Description

Configuring the `config.yml` with correct database parameters is very tedious.

### Describe your ideal solution

The application should use the `DATABASE_URL` environment variable and if not found, fall back to the database settings in `config.yml`.

### Workarounds or alternatives

```bash
#!/usr/bin/env sh

export DATABASE_USER=$(echo $DATABASE_URL | grep -oP "postgres://\K(.+?):" | cut -d: -f1)
export DATABASE_PASSWORD=$(echo $DATABASE_URL | grep -oP "postgres://.*:\K(.+?)@" | cut -d@ -f1)
export DATABASE_HOST=$(echo $DATABASE_URL | grep -oP "postgres://.*@\K(.+?):" | cut -d: -f1)
export DATABASE_PORT=$(echo $DATABASE_URL | grep -oP "postgres://.*@.*:\K(\d+)/" | cut -d/ -f1)
export DATABASE_NAME=$(echo $DATABASE_URL | grep -oP "postgres://.*@.*:.*/\K(.+?)$")

mkdir -p /config

(cat /config.yml) | envsub > /config/config.yaml

/hanko migrate up
/hanko serve public
```

### Hanko Version

v0.3.1

**Comment by mihailtd** [comment]
The title said "Support DATABASE_URL environment variable"
Indeed Hanko now supports database.url in its config, which is convenient however it doesn't support environment variables when it comes to database configuration.
This would be helpful; for example, I am using a postgres operator for Kubernetes which creates a secret with the database credentials. This is preferred to the alternative proposed in the example here - storing them in a configmap. 
There is no easy way of getting the database URL from a secret into the config file of Hanko.
If Hanko supported `DATABASE_URL` as an environment variable, it would make this much easier.

**Comment by IgnisDa** [comment]
If I understand correctly, environment variables are supported by hanko https://github.com/teamhanko/hanko/blob/main/backend/docs/Config.md#hanko-backend-config

**Comment by mihailtd** [comment]
@IgnisDa thanks! I missed that from the documentation
I was using DATABASE_URL as an env variable but trying do an `envsubst` to place it it `config.yaml`.
The problem I had was that I was running a very old `hanko:main` image, since I used the main tag, and never downloaded a new one.

thanks again!
