### ISSUE TITLE
WebAuthn - Add DELETE endpoint for WebAuthn Credentials

### ISSUE THREAD

**Issue by Happy2C0de** [teamhanko/hanko#499]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Description

First of all: Hanko's efforts are great. Thank you very much! 👍 

**Context:**
Currently, there is no option to delete a registered WebAuthn authenticator.
See: https://docs.hanko.io/api/public#tag/WebAuthn

**User Story:**
As a user, I would like to delete certain WebAuthn Credentials.

### Describe your ideal solution

Add a DELETE endpoint for WebAuthn Credentials.

### Workarounds or alternatives

-

### Hanko Version

v0.3.2

**Comment by like-a-bause** [comment]
Will be shipped soon in this PR #495

**Comment by Happy2C0de** [comment]
Thanks @like-a-bause for the pointer!
Looking forward to it 👍

**Comment by FlxMgdnz** [comment]
The API and also a complete profile component with passkey management features are available now, see https://docs.hanko.io/api/public#tag/WebAuthn/operation/deleteCredential
