### ISSUE TITLE
Example: Deno Fresh

### ISSUE THREAD

**Issue by like-a-bause** [teamhanko/hanko#641]
An example for Deno Fresh would need the following:

- [x] Import via esm.sh: https://esm.sh/@teamhanko/hanko-elements@0.2.2-alpha
- [ ] a way to disable Server-Side-Rendering for the hanko-elements
- [ ] Add integration guide to docs

Currently when trying to integrate the hanko-elements we get an error:
```
error: Uncaught (in promise) ReferenceError: document is not defined
    at Object.N.exports [as insertStyleElement] (https://esm.sh/v111/@teamhanko/hanko-elements@0.2.2-alpha/deno/hanko-elements.js:2:33121)
    at Object.N.exports [as domAPI] (https://esm.sh/v111/@teamhanko/hanko-elements@0.2.2-alpha/deno/hanko-elements.js:3:606)
...
```
there is no DOM Api in SSR. We would need something like the dynamic function in next.js.
There is a issue at deno/fresh: https://github.com/denoland/fresh/issues/1061

**Comment by like-a-bause** [comment]
As a workaround you can use something like this:
```jsx
const code = `
 import { register } from 'https://esm.sh/@teamhanko/hanko-elements@0.2.2-alpha';

    register({ shadow: true });
    document.addEventListener('hankoAuthSuccess', (event) => {
        console.log(event);
        document.location.href = '/secured'
    })
`
export default function HankoLogin() {

  return (
    <div class="auth-container">
      <hanko-auth api="http://localhost:8000"></hanko-auth>
      <script type="module">
        {code}
      </script>
    </div>
  );
}
```

I hope there is a better way though...

**Comment by FlxMgdnz** [comment]
> /claim #641 Hello. Which branch is the pull req to be made in. I wish to participate in OSB. thank you.

Hey, just create your own branch from main.

**Comment by tobihans** [comment]
@kellymweu are you still on this? Or can I attempt it?

**Comment by kellymweu** [comment]
hello @tobihans, you can attempt it. Thank you
