### ISSUE TITLE
Health checks in docker images

### ISSUE THREAD

**Issue by IgnisDa** [teamhanko/hanko#697]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Description

I am trying to configure a [health check](https://docs.docker.com/engine/reference/builder/#healthcheck) in my Dockerfile. Here is the `test` command I use `[ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9000/.well-known/jwks.json" ]` However, since Hanko base image uses a `distroless` base image, utilities like `wget`, `curl` are not present in the base image.

Output of health check:

![image](https://user-images.githubusercontent.com/60938164/227702688-d3b18c7b-1a11-4e19-ad40-561954893add.png)

How can I configure a healthcheck for my Hanko service, in this case?

### Describe your ideal solution

Maybe we can use a base image of `alpine` instead of `distroless`. However, this might increase image size by a few MBs.

### Workarounds or alternatives

None that I know of 

### Hanko Version

v0.5.0

### Additional Context

Moreover, using `/.well-known/jwks.json` for public service's health check seems a bit hacky, it would be nice if there was a dedicated endpoint for it.

The admin service does not seem to have a health check endpoint at all.

**Comment by like-a-bause** [comment]
Hi there,
we have health endpoints on both public and admin services:
```
	health := e.Group("/health")
	health.GET("/alive", healthHandler.Alive)
	health.GET("/ready", healthHandler.Ready)
```
these are not listed in the api specification. Thanks for pointing that out.

For our production workloads we are running on kubernetes which has got external health checkers.
I would like to stay on distroless instead of alpine so my thinking is:
- [ ] Document the health endpoint in the api spec
- [ ] Implement a health check command in hanko which calls the http health endpoint via go

**Comment by IgnisDa** [comment]
>  Implement a health check command in hanko which calls the http health endpoint via go

Sounds good to me, I can make a PR.

**Comment by like-a-bause** [comment]
Awesome. Looking forward to it.

**Comment by IgnisDa** [comment]
>  Document the health endpoint in the api spec

@like-a-bause Regarding this, are the specs not auto-generated?
