### ISSUE TITLE
frontend-sdk: cookies set via SDK not valid for subdomains

### ISSUE THREAD

**Issue by lfleischmann** [teamhanko/hanko#699]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Description

Cookies set by the SDK (i.e. set in response to reading the `X-Auth-Token` header in case of frontend and Hanko API running on different domains) are not valid for subdomains. If my frontend runs on `yourapp.com` and I have another API running at `api.yourapp.com` then the cookie will only be valid for `yourapp.com` but not the `api` subdomain. This is because we do not set the `domain` attribute on creating the cookie: 

```javascript
_setAuthCookie(token: string) {
    const secure = !!this.api.match("^https://");
    Cookies.set(this.authCookieName, token, { secure }); // <- no domain set
}
```

From [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#domain_attribute):

> The Domain attribute specifies which hosts can receive a cookie. If the server does not specify a Domain, the browser defaults the domain to the same [host](https://developer.mozilla.org/en-US/docs/Glossary/Host) that set the cookie, excluding subdomains. If Domain is specified, then subdomains are always included. 

I think it is a viable scenario that users run another service on such a subdomain and want to use the JWT for authentication with said service as well.

### Describe your ideal solution

Set the domain when creating the cookie:

```javascript
_setAuthCookie(token: string) {
    const secure = !!this.api.match("^https://");
    Cookies.set(this.authCookieName, token, { secure , domain: "<DOMAIN>" }); // 
}
```

How to get the domain at this point:

1. Determine from current location (not sure how to do this in reliable/robust manner) or
2. Make it configurable and propagate via public configuration

### Hanko Version

v0.5.0

**Comment by IgnisDa** [comment]
@lfleischmann Any updates on this?
