### ISSUE TITLE
"Create a passkey" sometimes prompts to register hardware token instead of passkey on Brave/Chrome

### ISSUE THREAD

**Issue by cayblood** [teamhanko/hanko#702]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

I just wanted to share something weird I’ve observed with the Hanko user experience in Brave/Chrome. Every once in a while, after registering a new user and clicking on “Create a passkey,” the browser will offer to use a hardware token instead of create a browser-based passkey. Clicking on cancel and then retrying will then display the right option. I’m not sure why this happens and don’t know if it is a browser bug or a hanko bug.

### Reproducing the bug

Don't have a consistent way to reproduce, but as mentioned, creating a passkey occasionally will cause the bug to occur.

### Hanko Version

Hanko Cloud, hanko-elements 0.2.2-alpha, hanko-frontend-sdk 0.2.1-alpha

### OS

macOS

### OS Version

macOS Ventura Version 13.2.1 (22D68)

### Browser Version

Brave 1.49.128 (Chromium 111.0.5563.110 - official build - arm64)

### Environment

Other (e.g. Kubernetes)

### Additional Context

Hanko Cloud tested on 27 Mar 2023
The following frontend libs:
@teamhanko/hanko-elements: 0.2.2-alpha
@teamhanko/hanko-frontend-sdk: 0.2.1-alpha

**Comment by FlxMgdnz** [comment]
This is most likely a browser issue that may be solved by now. Are you still seeing this behavior  @cayblood ?

**Comment by cayblood** [comment]
@FlxMgdnz I haven't observed it lately. Feel free to close this issue.
