### ISSUE TITLE
Next.js App/dir documentation request

### ISSUE THREAD

**Issue by EzraChai** [teamhanko/hanko#776]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Description

Next.js 13 App directory documentation

### Describe your ideal solution

Documentation

### Hanko Version

0.4.0-alpha

**Comment by EzraChai** [comment]
I think this documentation is only suitable for the pages/ directory.
I hope the documentation for the Next.js App/ directory will be coming out soon~

https://docs.hanko.io/guides/next

**Comment by ha-sante** [comment]
Same here @lfleischmann

**Comment by FlxMgdnz** [comment]
Hanko works fine with Next.js /app. We'll release updated docs and a new example app soon.

**Comment by FlxMgdnz** [comment]
We have a guide for app dir now https://docs.hanko.io/guides/next
