### ISSUE TITLE
hanko-elements: add event on WebComponent connected

### ISSUE THREAD

**Issue by jankal** [teamhanko/hanko#837]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Description

I want to be able to react to the finished mounting of the WebComponents. Conveniently there is a callback function `connectedCallback` provided by the browser.

### Describe your ideal solution

Make it possible to listen to the callback through the hanko frontend SDK.

E.g. like this:
```
import { register } from "@teamhanko/hanko-elements";

const { hanko } = await register("https://your-api.hanko.io/");

// Add a callback to be executed when the user is logged in and ready to be redirected.
const removeEventListener = hanko.elementConnectedCallback((event) => {
	// Your code...
})

// The `removeEventListener()` function removes the event listener
removeEventListener();
```

### Hanko Version

0.7.0

### Additional Context

@teamhanko/hanko-elements@0.5.5-beta

**Comment by bjoern-m** [comment]
Hi @jankal 
I took a look at it and tried to implement it. I can gladly share it with you, but I'm not entirely satisfied with it for some reason, perhaps because I don't know of any real-life use case for it and wondering if we could achieve more or less the same by awaiting the promise returned by the `await register(apiUrl)` function. Therefore, I would like to ask if you could assist me and maybe explain your use case to me?

**Comment by jankal** [comment]
Hi @bjoern-m 
Actually, this "problem" came up when trying to build a workaround for #836.
My idea was to just fill the `input[type="email"]` field using JS.
As the completion point of the `await register (apiUrl)` Promise is usually before the WebComponent was `connected` to the DOM, I cannot be sure of the `input[type="email"]` existing yet.

Additionally, we currently have no way of reacting to each of the WebComponent elements being `connected`.

Another possible use-case that comes to my mind is removing potential spinner / placeholder elements above the element when it's `connected`.
