### ISSUE TITLE
JWT: add nbf claim

### ISSUE THREAD

**Issue by jankal** [teamhanko/hanko#841]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Description

To ensure compatibility with as much JWT libraries as possible, I suggest adding an `nbf` claim as specified in [RFC 7519](https://www.rfc-editor.org/rfc/rfc7519) sect [4.1.5](https://www.rfc-editor.org/rfc/rfc7519.html#section-4.1.5).

### Hanko Version

0.7.0

**Comment by like-a-bause** [comment]
This would only make sense with a valid use-case. But I can't think of any where it makes sense to start a user session in the future.
Since nbf is optional, compatibility is not an issue.
Do you have an use-case for this? Otherwise I would mark this as "wontfix".

**Comment by jankal** [comment]
The `nbf` claim can be helpful for future features. Currently, I cannot see any real use-case anymore, as I was able to resolve my issues differently.
