### ISSUE TITLE
hanko-elements: Allow setting input background different from container background

### ISSUE THREAD

**Issue by jankal** [teamhanko/hanko#844]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Description

In my example app, I want to set the input background color to `white` while still keeping the elements' container background `grey`. Currently this is not possible (looked [here](https://github.com/teamhanko/hanko/tree/main/frontend/elements#ui-customization))

<img width="659" alt="image" src="https://github.com/teamhanko/hanko/assets/6324332/d67b231c-ec33-4eaa-9cc1-74d61535fdce">

### Describe your ideal solution

Add a new CSS variable like `--input-background` to allow for changing the input background color.

### Hanko Version

0.7.0

### Additional Context

@teamhanko/[hanko-elements@0.5.5-beta](mailto:hanko-elements@0.5.5-beta)

**Comment by bjoern-m** [comment]
Hi @jankal 

Would it be feasible for you to use the shadow part to change the background color?

```
hanko-auth::part(input) {
  background-color: white;
  -webkit-box-shadow: 0 0 0 50px white inset
}
```

If we were to add an --input-background variable, you would probably expect to be able to control the background colors of other states (e.g., disabled) of the input fields using CSS variables, and the same would likely apply to buttons and other elements. We had such a solution before, but we abandoned it because it led to an huge number of variables.

**Comment by jankal** [comment]
Hey @bjoern-m,

I think that works. Maybe we can document this possibility in the frontend guides somehow.
At least I am working with shadow DOMs for the first time in the context of this project, so I didn't event know about the [`::part()`](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) pseudo-selector syntax.

**Comment by bjoern-m** [comment]
Hi @jankal 

I have revised the README file of `hanko-elements` and added a few examples on how to use the shadow parts. Feel free to check out the [modified version](https://github.com/teamhanko/hanko/tree/main/frontend/elements#css-shadow-parts) and let me know if that's the information you needed. I think we should also consider providing a guide on [docs.hanko.io](https://docs.hanko.io) for this topic.

Best regards!

**Comment by jankal** [comment]
Hi @bjoern-m 

I think the added information in the README help a lot already.
From my side, we can close this.
