### ISSUE TITLE
hanko-server: change content-type of /.well-known/jwks.json

### ISSUE THREAD

**Issue by jankal** [teamhanko/hanko#850]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

Per [RFC 7517](https://datatracker.ietf.org/doc/html/rfc7517#section-8.5.1) the `/.well-known/jwks.json` can make use of the special Content-Type `application/jwk-set+json`

### Reproducing the bug

Use cURL to request the `/.well-known/jwks.json`:

```bash
$ curl -vvv https://login.cloud.hanko.io/.well-known/jwks.json
```

### Hanko Version

0.7.0

**Comment by like-a-bause** [comment]
The content type **application/json** is correct. jwk-set+json is more specific, so I'm relabeling as enhancement.
We talked about this and are unsure if this would do more harm in regards to compatibility.
Do you have an example where not returning this content type leads to an error?

**Comment by jankal** [comment]
I don't see any case where using `application/json` leads to an error right now.
I just came across this while reading the RFC and thus thought `application/jwk-set+json` would be more correct.

If we expect errors when adopting `application/jwk-set+json`, we probably shouldn't do it.

**Comment by like-a-bause** [comment]
We saw that keycloak also return as `application/json` so it's probably ok to do it that way. I agree that it would be good to conform to the spec in general.
A compromise could be to return `application/jwk-set+json` if that is what is specified in the Accept Header of the request?
