### ISSUE TITLE
Background of input remains transparent if using autofill in dark-mode apps

### ISSUE THREAD

**Issue by Ashutosh-Bhadauriya** [teamhanko/hanko#875]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

https://github.com/teamhanko/hanko/assets/62984427/c4d80d2d-9b00-4f73-b7eb-692155b65669

**How to fix it?**
`--background-color` should be same as background.

The bug is that we are giving `--background-color: transparent` inside hanko-auth, hanko-profile{} section, instead it should be the same as the actual background color, on which Hanko is added, which is `#262b35` in our case.

Reason: To override the default color of the autofill in the browser, it falls back to the background color that we have provided, which is transparent in our case, due to which the autofill background remains transparent.

### Reproducing the bug

Go to hanko cloud signup/in page
Chooose autofill for email

### Hanko Version

Not sure

### OS Hanko Backend

None

### OS

None

### Environment

None

**Comment by FlxMgdnz** [comment]
Out of scope here

**Comment by Ashutosh-Bhadauriya** [comment]
I still see this issue on cloud.hanko.io, I can fix it, is it possible the get the code access for hanko cloud?

**Comment by Ashutosh-Bhadauriya** [comment]
Yeah its in the hanko cloud and not in the component, I already mentioned this here and told @FlxMgdnz when I created this issue.

> --background-color should be same as background.
> 
> The bug is that we are giving --background-color: transparent inside hanko-auth, hanko-profile{} section, instead it should be the same as the actual background color, on which Hanko is added, which is #262b35 in our case.
> 
> Reason: To override the default color of the autofill in the browser, it falls back to the background color that we have provided, which is transparent in our case, due to which the autofill background remains transparent.

**Comment by Ashutosh-Bhadauriya** [comment]
But this should also have solved the issue i guess?

> Can be fixed by setting --background-color to the actual color of the surrounding app. Maybe we can improve the situation by removing transparent as default.

**Comment by FlxMgdnz** [comment]
The background-color default value is white, so I don't think we need to do anything other than changing the value for Hanko Cloud.

**Comment by Ashutosh-Bhadauriya** [comment]
Yeah we just need to do, `--background-color: #262b35` in hanko cloud (where the css of hanko components resides)
