### ISSUE TITLE
frontend example react app failed to install @teamhanko/hanko-elements@^0.5.8-beta.

### ISSUE THREAD

**Issue by 8000milestones** [teamhanko/hanko#882]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

tried to run npm install at the latest frontend/examples/react app: got error message: 
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @teamhanko/hanko-elements@^0.5.8-beta.

What is the latest @teamhanko/hanko-elements that is usable today?

### Reproducing the bug

to reproduce:

1. git clone the repo
2. cd to react dir
3. run npm install

### Hanko Version

d97a1adde734fc09691a677fa6948919c87d9f79

### OS Hanko Backend

None

### OS Version Hanko Backend

macOS and ubuntu

### OS

macOS

### Environment

None

**Comment by like-a-bause** [comment]
We are using a workspace pattern here. So to get this running you have to
> cd frontend/
> npm install
> npm run start --workspace examples/react

If you do it like that the version of the elements in the file system (which may not be published yet) gets used.

We should think about adding a README to the frontend folder and altering the texts in the examples README:
https://github.com/teamhanko/hanko/blob/main/frontend/examples/react/README.md#run-development-server

**Comment by 8000milestones** [comment]
Thanks. I tried what you suggested. Still getting error, so I clone a fresh copy under a new directory: still got this error when running npm run start --workspace examples/react:

ERROR in src/HankoAuth.tsx:8:33

TS2307: Cannot find module '@teamhanko/hanko-elements' or its corresponding type declarations.
     6 | } from "react";
     7 | import { useNavigate } from "react-router-dom";
  >  8 | import { Hanko, register } from "@teamhanko/hanko-elements";
       |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
     9 | import styles from "./Todo.module.css";
    10 |
    11 | const api = process.env.REACT_APP_HANKO_API!;

**Comment by 8000milestones** [comment]
first tried on macOS, then tested again on Ubuntu. Same errors.

**Comment by like-a-bause** [comment]
Sorry I forgot on step:
> cd frontend/
> npm install
> npm run build
> npm run start --workspace examples/react

before you have to install turbo globally:
> npm install turbo --global

**Comment by 8000milestones** [comment]
It worked!. Thanks again for your guidance. Will continue to explore and learn. Really appreciate what your guys have built and plan to design a new system based on hanko passkeys infra. Keep up the good work!
