### ISSUE TITLE
DOM independent SDK

### ISSUE THREAD

**Issue by paul-asvb** [teamhanko/hanko#887]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Description

# Problem

Using hanko in Frontend-Framework (vue) in a hybrid (static / SSR) setup (nuxt) makes using the prebuild elements impossible.
Especially when one tries to use a custom UI.

### Describe your ideal solution

hanko-frontend-sdk without using the browser API

### Workarounds or alternatives

What i am testing at the moment: integrating with the REST-API.

### Hanko Version

0.5.8-beta

**Comment by like-a-bause** [comment]
Have you tried out https://github.com/nuxt-modules/hanko yet?

**Comment by paul-asvb** [comment]
Thanks for the fast reply, yes. My expectation was that useHanko() returns something that wraps hanko-frontend-sdk. Is that wrong?

**Comment by McPizza0** [comment]
@paul-asvb that is how it currently works.
e.g. `useHanko()?.user.create(email.value)` works out of the box
Please share version number if it isnt working
