### ISSUE TITLE
Disable sign-ups

### ISSUE THREAD

**Issue by johnbchron** [teamhanko/hanko#911]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Description

I would like a way to fully disable sign ups. My application involves restricting logins to only users whose emails are already inserted into the database, and it wouldn't make sense for me to allow other people to sign up. Aside from manually re-implementing the frontend components to check the db for an account before allowing sign-up, I can't find a solution that exists.

### Describe your ideal solution

A flag in the config file would suffice. Something `account.allow_creation`.

### Workarounds or alternatives

As I said above, I could re-implement or modify the existing frontend components, but that seems unnecessary.

### Hanko Version

0.8.0

**Comment by FlxMgdnz** [comment]
Thanks for mentioning this! We've actually heard similar feedback in the past and are already working on planning this feature.

**Comment by FlxMgdnz** [comment]
@irby Awesome! A relatively simple solution for disabling sign-ups (like @johnbchron's suggestion) is desirable, so yes, you're welcome do it. Hanko Elements would probably have to respect the setting and handle unwanted sign-up attempts gracefully. Also, the heading of <hanko-auth> ("Sign in or sign up") should probably be changed depending on the setting.

**Comment by irby** [comment]
@FlxMgdnz this issue should be good to close out 😁
