### ISSUE TITLE
frontend(examples): angular example no longer working

### ISSUE THREAD

**Issue by lfleischmann** [teamhanko/hanko#926]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

The Angular example no longer works properly. There are two failure scenarios:

1. When starting the Angular example from the `frontend/examples/angular` directory via `npm run start` using a Hanko Cloud instance and specifying its corresponding API URL  in the `frontend/examples/angular/src/environment/environment.ts` file, the application does start up but the <hanko-auth> element cannot be rendered on visiting the default `http://localhost:8888`. Instead, there is a console error in the browser: 

```
ERROR TypeError: Cannot read properties of null (reading 'bindingStartIndex')
    at ɵɵelementStart (core.mjs:13575:46)
    at Module.ɵɵelement (core.mjs:13656:5)
    at AppComponent_Template (app.component.html:1:1)
    at executeTemplate (core.mjs:10457:9)
    at renderView (core.mjs:10279:13)
    at renderComponent (core.mjs:11450:5)
    at renderChildComponents (core.mjs:10138:9)
    at renderView (core.mjs:10304:13)
    at ComponentFactory.create (core.mjs:12194:13)
    at ApplicationRef.bootstrap (core.mjs:25271:42)
```

2. When using the `docker compose -f deploy/docker-compose/base.yaml -f deploy/docker-compose/todo-angular.yaml -p "hanko-todo-angular" up --build` command as described in the `frontend/README.md` file, the compose cluster starts up but any attempt to access `http://localhost:8888` results in a `404` response.

### Reproducing the bug

# Scenario 1:

1. Check out current state of the repository
1. Create account in Hanko Cloud
2. Set App URL to "http://localhost:8888"
3. In the `frontend/` directory run `npm install`
4. Open `frontend/examples/angular/src/environment/environment.ts` file and enter your Hanko Cloud Instance API URL
5. In the `frontend/examples/angular` directory, run `npm run start` (if it does not work, try another `npm install` in the `frontend` directory)
6. Go to `http://localhost:8888` in your browser
7. Open  your browsers developer tools
8. Observe above mentioned error

# Scenario 2:

1. Check out current state of the repository
3. In the repository root issue the following command on your shell (as described in `frontend/examples/README.md`): `docker compose -f deploy/docker-compose/base.yaml -f deploy/docker-compose/todo-angular.yaml -p "hanko-todo-angular" up --build`
4. Go to `http://localhost:8888` in your browser
5. Observe a `404` with an error message `Cannot GET /` in your browser 

### Hanko Version

e7dc097baf4ca9930f3b082335f8d27c48384fed

### OS Hanko Backend

None

### OS

None

### Environment

None

**Comment by rishi-raj-jain** [comment]
@FlxMgdnz Can I work on this? Will I get the bounty if submitted earlier?

**Comment by FlxMgdnz** [comment]
> @FlxMgdnz Can I work on this? Will I get the bounty if submitted earlier?

Let's give @tobihans another day to answer.

**Comment by tobihans** [comment]
Hi there, sorry for being silent. I've been busy but I started working on it. I wasn't able to reproduce the issue exactly. I'm getting typescript errors (see below). So, I'm investigating that. Thanks.

```bash
> start
> ng serve --port 8888

✔ Browser application bundle generation complete.

Initial Chunk Files   | Names         |  Raw Size
vendor.js             | vendor        |   3.09 MB | 
polyfills.js          | polyfills     | 314.97 kB | 
styles.css, styles.js | styles        | 210.24 kB | 
main.js               | main          |  57.68 kB | 
runtime.js            | runtime       |   6.51 kB | 

                      | Initial Total |   3.67 MB

Build at: 2023-07-31T08:25:26.073Z - Hash: feca202432a234fd - Time: 4582ms

./src/app/services/hanko.services.ts:3:0-60 - Error: Module not found: Error: Can't resolve '@teamhanko/hanko-elements' in '/home/.../hanko/frontend/examples/angular/src/app/services'

Error: src/app/profile/profile.component.ts:23:51 - error TS7006: Parameter 'e' implicitly has an 'any' type.

23     this.hankoService.client.user.logout().catch((e) => (this.error = e));
                                                     ~


Error: src/app/services/hanko.services.ts:3:33 - error TS2307: Cannot find module '@teamhanko/hanko-elements' or its corresponding type declarations.

3 import { Hanko, register } from "@teamhanko/hanko-elements";
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: src/app/todo/todo.component.ts:111:51 - error TS7006: Parameter 'e' implicitly has an 'any' type.

111     this.hankoService.client.user.logout().catch((e) => (this.error = e));
                                                      ~




** Angular Live Development Server is listening on localhost:8888, open your browser on http://localhost:8888/ **


✖ Failed to compile.
```

**Comment by tobihans** [comment]
@rishi-raj-jain Please, feel free to pick it up. Time is really against me. Thanks.

**Comment by rishi-raj-jain** [comment]
@FlxMgdnz 

Please see https://github.com/teamhanko/hanko/pull/943#issuecomment-1662099693, we're just left with scenario 2.

**Comment by rishi-raj-jain** [comment]
@FlxMgdnz I hope the bounty stays to me and not to tobihans per https://github.com/teamhanko/hanko/issues/926#issuecomment-1662102956.

**Comment by tobihans** [comment]
> @FlxMgdnz I hope the bounty stays to me and not to tobihans per https://github.com/teamhanko/hanko/issues/926#issuecomment-1662102956.

Yes, don't worry. I'm no longer involved. The bounty will be given to you by the maintainers. The bot is just performing an automated action.

**Comment by rishi-raj-jain** [comment]
Thank you so much for the confirmation, @tobihans 🙌🏻
