### ISSUE TITLE
ci: configure stale issue workflow

### ISSUE THREAD

**Issue by lfleischmann** [teamhanko/hanko#927]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Description

There should be some mechanism for identifying certain issues as "stale" (e.g. if there is no response from issuer after a certain period of time) and automatically closing them. 

### Describe your ideal solution

There is an official GItHub [guide](https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues) describing how one might do this. 

### Hanko Version

any

**Comment by tungbq** [comment]
Hello @lfleischmann, do you need help on this issue?
I'd like to work on the CI task like this, may I pick up this task?

**Comment by tungbq** [comment]
Hi @lfleischmann,
Thanks for your kindly response. I've proposed the initial workflow in #934. Please have a look and review it. Thanks!
