### ISSUE TITLE
Replace Sonatype Lift

### ISSUE THREAD

**Issue by FlxMgdnz** [teamhanko/hanko#940]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Description

Sonatype Lift is retiring (and we're reminded on each PR that this is happening).

### Describe your ideal solution

Find a new code QA solution.

Maybe https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql

### Hanko Version

0.8.1

**Comment by ichistmeinname** [comment]
A possible alternative might be [Sonar](https://www.sonarsource.com/products/sonarqube/downloads/)? It’s free for open-source, if I remember correctly.
