### ISSUE TITLE
Add Python docs / middleware to Hanko Docs

### ISSUE THREAD

**Issue by FlxMgdnz** [teamhanko/hanko#975]
A snippet that shows a way to make Hanko JWTs work in a Python app would be a great addition to the docs.

**Comment by FlxMgdnz** [comment]
Please note that we can only accept docs with code that has actually been tested.

**Comment by ayusham001** [comment]
Hi @FlxMgdnz, is this issue still unresolved? I'd like to confirm before I invest any effort.
