### ISSUE TITLE
Sign in with Microsoft

### ISSUE THREAD

**Issue by FlxMgdnz** [teamhanko/hanko#976]
Add Microsoft as another OAuth provider for Hanko.

**Comment by sagar-kashyap** [comment]
Can you assign this to me

**Comment by sagar-kashyap** [comment]
@FlxMgdnz can you assign this to me.

**Comment by sagar-kashyap** [comment]
Hi @FlxMgdnz 
I am getting some difficulty while migrating. How to fix this??
`Migrator: problem creating schema migrations: couldn't start a new transaction: could not create new transaction: failed to connect to host=localhost user=postgres database=hanko: dial error (dial tcp [::1]:5432: connect: cannot assign requested address)`

**Comment by b4s36t4** [comment]
@FlxMgdnz Please watch the below demo video, if you're okay with the implementation, I will raise the PR and start the documentation as well, Thanks.!
https://github.com/teamhanko/hanko/assets/59088937/653e31d2-88e2-46c1-85ee-6cffd21865b0

**Comment by b4s36t4** [comment]
one key thing to note in the implementation is `email_verified` would always be true cause microsoft is not sending that key in neither of the tokens (`access_token` and `id_token`)

**Comment by FlxMgdnz** [comment]
Hey @b4s36t4, this looks good 👍🏼
