### ISSUE TITLE
Admin Dashboard for hanko API  

### ISSUE THREAD

**Issue by yescine** [teamhanko/hanko#978]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Description

I installed hanko locally, the admin api doesn 't offer any web ui so we can visualize basic data and informations.

### Describe your ideal solution

offer basic Admin UI to visualize most important Data 

### Hanko Version

latest commit 3a993fe501932261c68472e96974c876d2fc7715

**Comment by FlxMgdnz** [comment]
This would certainly be nice to have, but we can't work on it at the moment.

**Comment by chandu** [comment]
@yescine @FlxMgdnz Would it be possible to outline what is features are expected of the Admin UI?

**Comment by yescine** [comment]
@chandu I already switched to https://github.com/casdoor/casdoor identities management
The outline of the feautures simple table of registered user account and their provider with simple back-office update operations
