### ISSUE TITLE
Following NextJS Guide doesn't work

### ISSUE THREAD

**Issue by coffeedoughnuts** [teamhanko/hanko#999]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

Hi,

I have followed the nextjs guide [here](https://docs.hanko.io/guides/next) and I get the following two errors:

1. in vscode, typescript says: `Module '"@teamhanko/hanko-elements"' has no exported member 'Hanko'.` on the line `import { register, Hanko } from "@teamhanko/hanko-elements";`
2. when running the app locally (using `npm run dev`) the login screen shows a generic error UI and the terminal outputs: `ReferenceError: CustomEvent is not defined`

### Reproducing the bug

1. `npx create-next-app@13.4.19 repro`
2. follow the steps at https://docs.hanko.io/guides/next
3. `npx tsc` to repro the first bug
4. `npm run dev`
5. navigate to `localhost:3000/login` to repro the second bug

### Logs

```Shell
npm run dev                                            

> app@0.1.0 dev
> next dev

- info Loaded env from [redacted].env
- ready started server on [::]:3000, url: http://localhost:3000
- event compiled client and server successfully in 227 ms (20 modules)
- wait compiling...
- event compiled client and server successfully in 103 ms (20 modules)
- info Loaded env from [redacted].env
- info Loaded env from [redacted].env
- wait compiling /login/page (client and server)...

warn - No utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CSS configuration.
warn - https://tailwindcss.com/docs/content-configuration
- event compiled client and server successfully in 746 ms (388 modules)
- wait compiling...
- event compiled successfully in 49 ms (222 modules)
- error node_modules/@teamhanko/hanko-elements/dist/elements.js (2:54703) @ eval
- error ReferenceError: CustomEvent is not defined
    at __webpack_require__ ([redacted]/.next/server/webpack-runtime.js:33:42)
    at eval (./components/hanko/auth.tsx:11:83)
    at (ssr)/./components/hanko/auth.tsx ([redacted]/.next/server/app/login/page.js:315:1)
    at __webpack_require__ ([redacted]/.next/server/webpack-runtime.js:33:42)
null
- wait compiling /favicon.ico/route (client and server)...
- event compiled client and server successfully in 141 ms (443 modules)
```

### Configuration

```yml
# package.json

{
  "name": "app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@teamhanko/hanko-elements": "0.8.3",
    "@types/node": "20.5.7",
    "@types/react": "18.2.21",
    "@types/react-dom": "18.2.7",
    "autoprefixer": "10.4.15",
    "eslint": "8.48.0",
    "eslint-config-next": "13.4.19",
    "jose": "^4.14.4",
    "next": "13.4.19",
    "postcss": "8.4.29",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "tailwindcss": "3.3.3",
    "typescript": "5.2.2"
  }
}
```

### Hanko Version

0.8.3

### OS Hanko Backend

None

### OS

macOS

### OS Version

13.5.1 

### Browser Version

Chrome Version 116.0.5845.140 (Official Build) (arm64)

### Environment

None

**Comment by Ashutosh-Bhadauriya** [comment]
@coffeedoughnuts are you using next's app directory or pages? 

For the first problem, `moduleResolution: bundler`  value in the tsconfig introduced with typescript 5 might be causing the problem. You can use ts-ignore for that as of now, as we don't have the fix yet.

Also, you can take a look at this starter repo, if it helps: https://github.com/teamhanko/hanko-nextjs-starter

**Comment by coffeedoughnuts** [comment]
I am using the app directory (all my answers to create-next-app's interactive setup were the default)

**Comment by Ashutosh-Bhadauriya** [comment]
Can you please take at the repo I shared, it is based on the nextjs docs, and everything works. It uses pnpm btw

**Comment by coffeedoughnuts** [comment]
I cloned that repo, but used npm instead of pnpm because I don't have that tool installed, and the issue with the `CustomEvent is not defined` is the same.

is `@teamhanko/hanko-elements` only compatible with pnpm?

**Comment by Ashutosh-Bhadauriya** [comment]
No, its compatible with npm too, let me try using npm and get back to you

**Comment by IgnisDa** [comment]
@Ashutosh-Bhadauriya I am getting this error too: `Module '"@teamhanko/hanko-elements"' has no exported member 'Hanko'`

I am using `"@teamhanko/hanko-elements": "0.8.3"`.

**Comment by IgnisDa** [comment]
This is the error: 
![image](https://github.com/teamhanko/hanko/assets/60938164/2a42ed21-a5fa-4f37-b474-c5489fd14034)

Something that might be helpful is that it is a pnpm workspace.

**Comment by Ashutosh-Bhadauriya** [comment]
@coffeedoughnuts I tried it using npm, it's working perfectly fine. Please have a look at this repo if it helps, it uses npm
https://github.com/Ashutosh-Bhadauriya/hanko-next-npm

**Comment by Ashutosh-Bhadauriya** [comment]
@IgnisDa  `moduleResolution: bundler ` value in the tsconfig introduced with typescript 5 might be causing the problem. You can use `ts-ignore` for that as of now, as we don't have the fix yet.

**Comment by coffeedoughnuts** [comment]
Same issue I'm afraid. Here's a demo of the issue using your repo: _[YouTube](https://www.youtube.com/watch?v=8hJehvo-GMc)_

**Comment by Esther-Lita** [comment]
Hey there! the UI issue you mention is usually fixed in your Hanko Cloud dashboard. In your project configuration, the project URL must be the one you’re hosting/testing, in this case is "http://localhost:3000". You can change it back to the hosted URL once the project is published. Hope this help you 🙏🏽

**Comment by coffeedoughnuts** [comment]
Hi,

Making that change solves my issue - thanks.

Can I suggest mentioning this in the NextJS integration guide? Also, supporting multiple application URLs would be quite convenient (or some other mechanism that would support both local development and deployed apps)

Lastly, catching this scenario and displaying a useful error message from the app would be super helpful.

Thanks for your help
